### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by nickzuber** [OrN/rscplus#50]
I noticed that you do a lot of monkey patching in order to inject your methods into the actual game client.

For example:

```java
/* 
 * src/Client/JClassPatcher.java 
 */

// Chat menu
hookClassVariable(methodNode, "client", "yd", "Lqa;", "Game/Menu", "chat_menu", "Ljava/lang/Object;", true, false);
hookClassVariable(methodNode, "client", "Fh", "I", "Game/Menu", "chat_type1", "I", true, false);
hookClassVariable(methodNode, "client", "bh", "I", "Game/Menu", "chat_input", "I", true, false);
hookClassVariable(methodNode, "client", "ud", "I", "Game/Menu", "chat_type2", "I", true, false);
hookClassVariable(methodNode, "client", "mc", "I", "Game/Menu", "chat_type3", "I", true, false);
```

The owners, variables, and descriptions you pass to `hookClassVariable` seem really specific — how do you know what these are in the first place? Is there some kind of API we can consult to be able to inject functions into specific areas of the client? 

I'd really like to contribute with new features, but don't know where to begin when it comes to writing patches like this. Is there some kind of document to reference or something?

**Comment by Hubcapp** [comment]
I didn't work on that, but iirc it was a lot of guess work. A patch for the rsc came out somewhat recently (possibly a year ago now??) where Jagex had to update their certificate. This jumbled all the variable names, and rather than find them all again (apparently a tedious process with no automation) rsc+  now downloads the old version of the client to patch instead, which is apparently still compatible since Jagex didn't actually change anything substantial.

To begin finding variables you're interested in manually, try to see if you can find related functions in a class that's already being used, then in that class, look at all declared variables, and post each value to the screen to see if they line up with the feature you want to alter. A memory inspector is useful.

I think a certain botting client may have went open source with a tutorial on finding these values if I remember, but I don't know if that's true or not, it's been a while and I never looked at it too closely.
